# Generated by Django 3.0.2 on 2020-08-27 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200806_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='descriptions',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
